GET  http://127.0.0.1:8000/users
Accept: application/json
Content-Type: application/json

{

}
###

POST http://127.0.0.1:8000/users
Accept: application/json
Content-Type: application/json

{
    "name": "Tami",
    "email": "tami@mail.com"
}
###
GET  http://127.0.0.1:8000/users/12/notes
Accept: application/json
Content-Type: application/json

{
    
}
###
GET  http://127.0.0.1:8000/users/12/notes/67
Accept: application/json
Content-Type: application/json

{
    
}
###
POST  http://127.0.0.1:8000/users/12/notes
Accept: application/json
Content-Type: application/json

{
  "user_id" : 12,
  "title": "A note for user 12",
  "content": "This is a new note"
}
###
PUT  http://127.0.0.1:8000/users/12/notes/67
Accept: application/json
Content-Type: application/json

{
  "title": "edited",
  "content": "This is an edited note"
}

###
DELETE  http://localhost:8000/users/11/notes/4
Accept: application/json
Content-Type: application/json

{

}
###
GET  http://localhost:8000/notes
Accept: application/json
Content-Type: application/json

{

}
