GET  http://127.0.0.1:8000/users/11
Accept: application/json
Content-Type: application/json

{
    
}
###


GET  http://127.0.0.1:8000/users
Accept: application/json
Content-Type: application/json

{

}
###

POST http://127.0.0.1:8000/users
Accept: application/json
Content-Type: application/json

{
    "name": "res",
    "email": "res@mail.com"
}
###
GET  http://127.0.0.1:8000/users/11/notes/3
Accept: application/json
Content-Type: application/json

{
    
}
###
PUT  http://127.0.0.1:8000/users/11/notes/3
Accept: application/json
Content-Type: application/json

{
  "title": "edited",
  "content": "This is an edited note"
}

###
DELETE  http://localhost:8000/users/11/notes/3
Accept: application/json
Content-Type: application/json

{

}
